# Generated by Django 4.2.25 on 2025-11-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kclite_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinginfo',
            old_name='cvv',
            new_name='card_last4',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='number_id',
        ),
        migrations.RemoveField(
            model_name='numberdetails',
            name='did_uuid',
        ),
        migrations.RemoveField(
            model_name='numberdetails',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='twilio_token',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='payment_provider_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='direction',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kclite_backend_app.numberdetails'),
        ),
        migrations.AddField(
            model_name='logs',
            name='twilio_call_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kclite_backend_app.users'),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='acl_ip_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='acl_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='byoc_trunk_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='connection_policy_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='did_urn',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='inbound_trunk_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='outbound_trunk_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='sip_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='sip_domain_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='sip_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='kclite_backend_app.users'),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='verification_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='numberdetails',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='users',
            name='apple_sub',
            field=models.CharField(blank=True, help_text='Unique Apple user identifier (sub claim).', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='kclite_backend_app.subscriptionplans'),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_infos', to='kclite_backend_app.users'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='kclite_backend_app.users'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='destination_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logs',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='source_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='numberdetails',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numberdetails',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='numberdetails',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active', 'Active'), ('failed', 'Failed'), ('suspended', 'Suspended')], default='pending_verification', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='TelecomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_subaccount_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('twilio_api_key_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('twilio_api_key_secret', models.CharField(blank=True, max_length=128, null=True)),
                ('twilio_twiml_app_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('default_caller_id', models.CharField(blank=True, max_length=32, null=True)),
                ('didww_customer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telecom_profile', to='kclite_backend_app.users')),
            ],
        ),
    ]
