# Generated by Django 5.2.7 on 2025-12-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kclite_backend_app', '0002_rename_cvv_billinginfo_card_last4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberdetails',
            name='acl_ip_sid',
        ),
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='credits_left',
        ),
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='total_credits',
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='descripton',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='credits_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telecomprofile',
            name='twilio_subaccount_sid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
