"""
Django settings for kclite_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, defaults
    DEBUG=(bool, False),
    DIDWW_API_SANDBOX=(bool, False),
)
# read .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

SECRET_KEY = env("SECRET_KEY", default="fallback-secret-key")
DEBUG = env("DEBUG")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'kclite_backend_app.apps.KcliteBackendAppConfig', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', 
]

ROOT_URLCONF = 'kclite_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kclite_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
   "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "mydb"),
        "USER": os.getenv("POSTGRES_USER", "myuser"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "mypassword"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BASE_URL = env("BASE_URL")

REDIS_URL = env("REDIS_URL", default="redis://yAco1mOwrPst20wVrv6DE40xbmF0rY9BLCTapvOGoxlpGsFtCwYpwibHJeA6UgA3@localhost:6379/0")
REDIS_PORT = env("REDIS_PORT", default=6379)

# Twilio credentials
TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN")
TWILIO_API_KEY = env("TWILIO_API_KEY")
TWILIO_API_SECRET = env("TWILIO_API_SECRET")
TWIML_APP_SID = env("TWIML_APP_SID")
TWILIO_STATUS_CALLBACK_URL = f"{BASE_URL}/api/telecom/twilio/status/"
TWILIO_DIDWW_BYOC_SID = env("TWILIO_DIDWW_BYOC_SID")
TWILIO_DEFAULT_CALLER_ID = env("TWILIO_DEFAULT_CALLER_ID")
TWILIO_VERIFY_SERVICE_SID = env("TWILIO_VERIFY_SERVICE_SID")
TWILIO_VALIDATION_FROM_NUMBER = env("TWILIO_VALIDATION_FROM_NUMBER")


# DIDWW credentials
DID_BASE_URL = env("DIDWW_BASE_URL")
DIDWW_API_URL = "https://api.didww.com/v3"
DIDWW_API_KEY = env("DIDWW_API_KEY")
DIDWW_API_SANDBOX = env("DIDWW_API_SANDBOX")
DIDWW_SMS_TRUNK_USERNAME = env("DIDWW_SMS_TRUNK_USERNAME")
DIDWW_SMS_TRUNK_PASSWORD = env("DIDWW_SMS_TRUNK_PASSWORD")
DIDWW_SMS_TRUNK_HOST = env("DIDWW_SMS_TRUNK_HOST")
DIDWW_ALLOWED_RTP_ADDRESS = env.list("IP_ADDRESSES", default=[])
DIDWW_ALLOWED_SIP_ADDRESS = env.list("DIDWW_SIP_IP_ADDRESS", default=[])

# in-memory channel layer
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}



# Tell Django "hey, use my Channels stack in asgi.py"
ASGI_APPLICATION = "kclite_backend.asgi.application"